object BuildDependenciesVersions {
    const val GOOGLE_SERVICE_VERSION = "4.3.15"
    const val GRADLE_ANDROID = "7.4.2"
    const val KOTLIN = "1.8.21"
    const val APPCOMPAT = "1.5.1"
    const val MATERIAL = "1.8.0"
    const val ANNOTATION = "1.5.0"
    const val COROUTINES = "1.6.1"
    const val ROOM = "2.4.2"
    const val RECYCLE_VIEW = "1.3.0"
    const val VIEWPAGER2 = "1.0.0"
    const val NAVIGATION = "2.6.0"
    const val LIFECYCLE = "2.5.1"
    const val CORE_KTX = "1.9.0"
    const val FRAGMENT_KTX = "1.5.4"
    const val ACTIVITY_KTX = "1.6.1"
    const val CONSTRAIN_LAYOUT = "2.1.4"
    const val SPLASHSCREEN = "1.0.0"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0"
    const val PAGING = "2.1.2"
    const val HILT = "2.47"
    const val HILT_EXT = "1.0.0"
    const val TIMBER = "5.0.1"
    const val RETROFIT = "2.9.0"
    const val OKHTTP = "4.10.0"
    const val OKHTTP_LOGGING = "3.14.9"
    const val MOSHI = "1.14.0"
    const val LEAKCANARY = "2.9.1"
    const val RX_VERSION = "3.0.0"
    const val WORK_KTX = "2.7.1"
    const val WORK_HILT = "1.0.0"
    const val STARTUP = "1.1.1"
    const val JAVAX_INJECT_VERSION = "1"
    // const val SECURITY_CRYPTO = "1.0.0"
    const val PREFERENCE = "1.2.0"
    const val MULTIDEX = "2.0.1"
    const val PLACES = "3.1.0"

    // Coil - Image Loader
    const val COIL = "2.4.0"
    // Tests
    const val TEST = "1.3.0"
    const val EXT = "1.1.3"
    const val JUNIT = "4.13.2"
    const val ESPRESSO = "3.4.0"
    const val FLEXBOX = "3.0.0"
}